<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FatCat.LogReader.Razor</RootNamespace>
    <AssemblyName>FatCatLogReaderRazor</AssemblyName>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" Version="1.2.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
  </ItemGroup>

</Project>
